[package]
name = "micropython-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
micropython-sys = { path = "../micropython-sys" }
thiserror = { version = "2.0.20", default-features = false }

[build-dependencies]
micropython-build = { path = "../../../crates/micropython-build" }
micropython-manifest = { path = "../../../crates/micropython-manifest" }
