[package]
name = "mpy-rs"
version = "0.1.0"
edition = "2024"

[features]
default = ["install"]
install = ["dep:tar", "dep:zstd"]

[dependencies]
anyhow = "1.0.104"
blake3 = "1.8.6"
clap = { version = "4.6.6", features = ["derive"] }
micropython-depfile = { path = "../micropython-depfile" }
micropython-manifest = { path = "../micropython-manifest" }
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tar = { version = "0.4.46", optional = true }
tempfile = "3.27.0"
walkdir = "2.5.0"
zstd = { version = "0.13.3", optional = true }

[build-dependencies]
ignore = "0.4.33"
tar = { version = "0.4.46", optional = true }
zstd = { version = "0.13.3", optional = true }
