use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

mod config_names {
    include!("src/config_names.rs");
}

fn main() {
    println!("cargo::rerun-if-changed=src/config_names.rs");
    println!("cargo::rerun-if-changed=build.rs");

    let mut tail = String::from(
        r#"/* Generated by micropython-build/build.rs. Do not edit manually. */
#include "py/mpconfig.h"

#ifndef MP_STRINGIFY
#define MP_RS_MP_STRINGIFY_INNER(value) #value
#define MP_STRINGIFY(value) MP_RS_MP_STRINGIFY_INNER(value)
#endif

#define MP_RS_STRINGIFY_INNER(...) #__VA_ARGS__
#define MP_RS_STRINGIFY(...) MP_RS_STRINGIFY_INNER(__VA_ARGS__)
#define MP_RS_CONFIG(name) { #name, MP_RS_STRINGIFY(name) },

struct mp_rs_config_entry {
    const char *name;
    const char *value;
};

static const struct mp_rs_config_entry mp_rs_config[] = {
"#,
    );

    for name in config_names::CONFIG_NAMES {
        writeln!(tail, "#ifdef {name}").unwrap();
        writeln!(tail, "    MP_RS_CONFIG({name})").unwrap();
        tail.push_str("#endif\n");
    }
    tail.push_str("};\n");

    let output = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is not set")).join("tail.c");
    fs::write(output, tail).expect("failed to write generated tail.c");
}
