#!/usr/bin/env python3
"""Generate the Rust inventory of MicroPython configuration macros."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

DEFAULT_OUTPUT = Path(__file__).resolve().parent / "src" / "config_names.rs"
DEFINE_RE = re.compile(
    r"^[ \t]*#[ \t]*define[ \t]+(MICROPY_[A-Za-z0-9_]+)(.*)$",
    re.MULTILINE,
)
BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)


def strip_block_comments(source: str) -> str:
    """Remove block comments while preserving line boundaries."""

    return BLOCK_COMMENT_RE.sub(lambda match: "\n" * match.group(0).count("\n"), source)


def find_config_macros(source: str) -> list[str]:
    # Backslash-newline removal happens before directive processing in C.
    source = source.replace("\\\r\n", "").replace("\\\n", "")
    source = strip_block_comments(source)

    names: set[str] = set()
    for match in DEFINE_RE.finditer(source):
        # A function-like macro has no whitespace between its name and `(`.
        if match.group(2).startswith("("):
            continue
        names.add(match.group(1))

    return sorted(names)


def render_config_names(names: list[str]) -> str:
    entries = "\n".join(f'    "{name}",' for name in names)
    return f"""// Generated by gen_tail.py. Do not edit manually.

pub const CONFIG_NAMES: &[&str] = &[
{entries}
];
"""


class Args(argparse.Namespace):
    """Typed command-line arguments."""

    mpconfig_h: Path = Path()
    output: Path = DEFAULT_OUTPUT


def parse_args() -> Args:
    parser = argparse.ArgumentParser(
        description="Generate the MICROPY_* configuration macro inventory."
    )
    _ = parser.add_argument(
        "mpconfig_h",
        type=Path,
        help="path to MicroPython's py/mpconfig.h",
    )
    _ = parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"output path (default: {DEFAULT_OUTPUT})",
    )
    return parser.parse_args(namespace=Args())


def main() -> None:
    args = parse_args()
    mpconfig_h = args.mpconfig_h
    output = args.output

    if not mpconfig_h.is_file():
        raise SystemExit(f"error: mpconfig.h is not a file: {mpconfig_h}")

    source = mpconfig_h.read_text(encoding="utf-8")
    names = find_config_macros(source)
    if not names:
        raise SystemExit(
            f"error: no object-like MICROPY_* definitions found in {mpconfig_h}"
        )

    generated = render_config_names(names)
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.exists() or output.read_text(encoding="utf-8") != generated:
        _ = output.write_text(generated, encoding="utf-8")

    print(f"generated {output} with {len(names)} configuration macros")


if __name__ == "__main__":
    main()
